default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: photo_filter_development
  username: <%= ENV["PHOTO_FILTER_DEV_DATABASE_USERNAME"] %>
  password: <%= ENV["PHOTO_FILTER_DEV_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: photo_filter_test
  username: <%= ENV["PHOTO_FILTER_DEV_DATABASE_USERNAME"] %>
  password: <%= ENV["PHOTO_FILTER_DEV_DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: photo_filter_production
  username: photo_filter
  password: <%= ENV["PHOTO_FILTER_DATABASE_PASSWORD"] %>
